### ISSUE TITLE
ImportError: cannot import name 'HTCondorCluster' from 'dask_lxplus'

### ISSUE THREAD

**Issue by andreypz** [cernops/dask-lxplus#4]
Hello,
I am following a simple setup from https://batchdocs.web.cern.ch/specialpayload/dask.html
Namely, 
```
. /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/setup.sh
pip3 install --user dask_lxplus
export PYTHONPATH=~/.local/lib/python3.9/site-packages:$PYTHONPATH
```
then run the example script provided on that page with `python test_dask.py`
I get this error:
```
  from distributed.utils import tmpfile
Traceback (most recent call last):
  File "/afs/cern.ch/work/a/andrey/dask-test/test_dask.py", line 4, in <module>
    from dask_lxplus import HTCondorCluster
ImportError: cannot import name 'HTCondorCluster' from 'dask_lxplus' (/afs/cern.ch/user/a/andrey/.local/lib/python3.9/site-packages/dask_lxplus/__init__.py)
```
Any suggestions?

**Comment by bendylan** [comment]
Ah, error in those docs. Should be `CernCluster` not `HTCondorCluster` as per https://github.com/cernops/dask-lxplus#summary

**Comment by andreypz** [comment]
Ok, thanks. With this change, it seems to run on lxplus. It is still not fixed on the website though. Maybe worth doing that?

**Comment by bendylan** [comment]
The cern doc is correct now.
